openapi: 3.0.0
info:
  title: Flair API
  version: 1.0.0
paths:
  /api/v1/pucks:
    get:
      summary: Get all pucks
      operationId: getPucks
      responses:
        '200':
          description: A list of pucks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Puck'
  /api/v1/pucks/{id}/current-reading:
    get:
      summary: Get current reading for a puck
      operationId: getPuckCurrentReading
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Current reading of the puck
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reading'
  /api/v1/bridges:
    get:
      summary: Get all bridges
      operationId: getBridges
      responses:
        '200':
          description: A list of bridges
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bridge'
  /api/v1/bridges/{id}/current-reading:
    get:
      summary: Get current reading for a bridge
      operationId: getBridgeCurrentReading
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Current reading of the bridge
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BridgeReading'
  /api/v1/rooms:
    get:
      summary: Get all rooms
      operationId: getRooms
      responses:
        '200':
          description: A list of rooms
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Room'
  /api/v1/rooms/{id}/set-point:
    patch:
      summary: Adjust room set point
      operationId: patchRoomSetPoint
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                setPoint:
                  type: number
                  format: float
      responses:
        '200':
          description: Room set point adjusted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'
  /api/v1/structures:
    get:
      summary: Get all structures
      operationId: getStructures
      responses:
        '200':
          description: A list of structures
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Structure'
  /api/v1/structures/{id}:
    patch:
      summary: Update structure details
      operationId: patchStructure
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                location:
                  type: string
      responses:
        '200':
          description: Structure details updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Structure'
components:
  schemas:
    Puck:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        location:
          type: string
        status:
          type: string
        createdAt:
          type: string
          format: date-time
    Reading:
      type: object
      properties:
        temperature:
          type: number
          format: float
        humidity:
          type: number
          format: float
        battery:
          type: number
          format: float
        timestamp:
          type: string
          format: date-time
    Bridge:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        location:
          type: string
        status:
          type: string
        createdAt:
          type: string
          format: date-time
    BridgeReading:
      type: object
      properties:
        temperature:
          type: number
          format: float
        humidity:
          type: number
          format: float
        signalStrength:
          type: number
          format: float
        timestamp:
          type: string
          format: date-time
    Room:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        location:
          type: string
        status:
          type: string
        createdAt:
          type: string
          format: date-time
    Structure:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        location:
          type: string
        createdAt:
          type: string
          format: date-time
