openapi: 3.0.0
info:
  title: Flair API - Structures
  version: 1.0.0
paths:
  /api/v1/structures:
    get:
      summary: Get all structures
      operationId: getStructures
      responses:
        '200':
          description: A list of structures
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Structure'
  /api/v1/structures/{id}:
    patch:
      summary: Update structure details
      operationId: patchStructure
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                location:
                  type: string
      responses:
        '200':
          description: Structure details updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Structure'
components:
  schemas:
    Structure:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        location:
          type: string
        createdAt:
          type: string
          format: date-time
