# yaml-language-server: $schema=https://raw.githubusercontent.com/deepmap/oapi-codegen/HEAD/configuration-schema.json
package: structures
output: structures/structures.gen.go
generate:
  models: true
  client: true