# yaml-language-server: $schema=https://raw.githubusercontent.com/deepmap/oapi-codegen/HEAD/configuration-schema.json
package: bridges
output: bridges/bridges.gen.go
generate:
  models: true
  client: true