openapi: 3.0.0
info:
  title: Flair API - Pucks
  version: 1.0.0
paths:
  /api/pucks:
    get:
      summary: Get all pucks
      operationId: getPucks
      responses:
        '200':
          description: A list of pucks
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Puck'
  /api/pucks/{id}/current-reading:
    get:
      summary: Get current reading for a puck
      operationId: getPuckCurrentReading
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Current reading of the puck
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Reading'
components:
  schemas:
    Puck:
      type: object
      properties:
        type:
          type: string
        attributes:
          type: object
          properties:
            puck-display-color:
              type: string
            name:
              type: string
            bluetooth-tx-power-mw:
              type: integer
            sub-ghz-radio-tx-power-mw:
              type: integer
              nullable: true
            beacon-interval-ms:
              type: integer
            ir-download:
              type: boolean
            created-at:
              type: string
              format: date-time
            is-gateway:
              type: boolean
            drop-rate:
              type: number
              format: float
            current-humidity:
              type: integer
            temperature-offset-override-c:
              type: number
              format: float
              nullable: true
            orientation:
              type: string
            temperature-offset-c:
              type: number
              format: float
              nullable: true
            updated-at:
              type: string
              format: date-time
            current-rssi:
              type: integer
            current-temperature-c:
              type: number
              format: float
            ir-setup-enabled:
              type: boolean
              nullable: true
            demo-mode:
              type: integer
            humidity-offset:
              type: number
              format: float
              nullable: true
            display-number:
              type: string
            reporting-interval-ds:
              type: integer
            inactive:
              type: boolean
            oauth-app-assigned-at:
              type: string
              format: date-time
              nullable: true
        id:
          type: string
        relationships:
          type: object
          properties:
            room:
              type: object
              properties:
                links:
                  type: object
                  properties:
                    self:
                      type: string
                    related:
                      type: string
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    id:
                      type: string
    Reading:
      type: object
      properties:
        type:
          type: string
        attributes:
          type: object
          properties:
            puck-display-color:
              type: string
            name:
              type: string
            bluetooth-tx-power-mw:
              type: integer
            sub-ghz-radio-tx-power-mw:
              type: integer
              nullable: true
            beacon-interval-ms:
              type: integer
            ir-download:
              type: boolean
            created-at:
              type: string
              format: date-time
            is-gateway:
              type: boolean
            drop-rate:
              type: number
              format: float
            current-humidity:
              type: integer
            temperature-offset-override-c:
              type: number
              format: float
              nullable: true
            orientation:
              type: string
            temperature-offset-c:
              type: number
              format: float
              nullable: true
            updated-at:
              type: string
              format: date-time
            current-rssi:
              type: integer
            current-temperature-c:
              type: number
              format: float
            ir-setup-enabled:
              type: boolean
              nullable: true
            demo-mode:
              type: integer
            humidity-offset:
              type: number
              format: float
              nullable: true
            display-number:
              type: string
            reporting-interval-ds:
              type: integer
            inactive:
              type: boolean
            oauth-app-assigned-at:
              type: string
              format: date-time
              nullable: true
        id:
          type: string
        relationships:
          type: object
          properties:
            room:
              type: object
              properties:
                links:
                  type: object
                  properties:
                    self:
                      type: string
                    related:
                      type: string
                data:
                  type: object
                  properties:
                    type:
                      type: string
                    id:
                      type: string
